spring.application.name=member
server.port=8081
spring.h2.console.enabled=true

#set fix URL
spring.datasource.url=jdbc:h2:mem:member

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true